name: Daily URL Check

on:
  schedule:
    # 每天 UTC 时间 8:00 运行（可以根据你的时区调整）
    - cron: '0 14 * * *'

jobs:
  check_urls:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Visit multiple URLs and check status
      run: |
        # 定义需要访问的URL列表
        urls=(
          "https://dy.aaqq.site/api.php/timming/index.html?enforce=1&name=okziyuan"
          "https://dy.aaqq.site/api.php/timming/index.html?enforce=1&name=yayaziyuan"
          "https://dy.aaqq.site/api.php/timming/index.html?enforce=1&name=nnziyuan"
          "https://dy.aaqq.site/"
        )

        # 使用curl访问每个URL并检查HTTP状态码
        for url in "${urls[@]}"; do
          echo "Visiting $url"
          # 获取HTTP状态码
          status_code=$(curl -o /dev/null -s -w "%{http_code}" "$url")
          
          # 检查状态码是否为200
          if [ "$status_code" -eq 200 ]; then
            echo "✅ Success: $url returned $status_code"
          else
            echo "❌ Failure: $url returned $status_code"
            exit 1  # 如果有失败，退出并标记为失败
          fi
        done
